---
title: Traffic Data Analysis
output: html_document
---


### loading data
```{r}
library(dplyr)
df <- read.csv("all-semi-unique.csv")

```
### removing advertisments information
```{r}
cols <- grep("ad/*",names(df),value=F)
df2 <- df[,-cols]
```
### checking for columns with only one value
```{r}
unique(df2$rd.rp.type)
df2 <- subset(df2,select=-c(rd.rp.type))
unique(df2$rd.img)
unique(df2$rd.cl)
df2 <- subset(df2,select=-c(rd.cl))
```
### removing some columns
```{r}
df2 <- subset(df2,select=-c(rd.img))
```
### check if for duplicates in rows
```{r}
df3 <- subset(df2,select=-c(rd.hr,rd.mn,rd.rp.hr,rd.rp.mn,crawl_date))
df3 <- df3[!duplicated(df3),]
```
### add new columns for the dates of the road and comment
```{r}
x <- strptime(df2[,"crawl_date"],format = "%a %b %d %H:%M",tz = "UTC")
hrs <- function(u) {
 x <- u * 3600
 return(x)
}
mns <- function(m) {
 x <- m * 60
 return(x)
}
df2$tmp_date <- x
df2 <- mutate(df2, date= tmp_date-hrs(rd.hr)-mns(rd.mn))
df2 <- mutate(df2, rp.date= tmp_date-hrs(rd.rp.hr)-mns(rd.rp.mn))
df2 <- subset(df2,select=-c(rd.hr,rd.mn,rd.rp.hr,rd.rp.mn,crawl_date,tmp_date))
df2 <- df2[!duplicated(df2),]
```
